spring.application.name=employee-management-system
# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/employee_management_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Nimai@123

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true